// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uarlodwavzmgezguxygk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhcmxvZHdhdnptZ2V6Z3V4eWdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNDc1NDgsImV4cCI6MjA3MTkyMzU0OH0.9wr0NzizOn7AlBJnVbnb7j6APC5vcNdtP3YOU0XRlfE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});